### PR TITLE
Fixes the URL, since plex updated thier site

### PR DESCRIPTION
**Pull request by thesymbol**
The plex.tv website updated and ?chanell=plexpass is not available to
normal plex users (they might have changed the url for plexpass releases aswell?) and is therefore broken.
someone with plexpass should check if this is working to get plexpass release of the software (since
i do not have that i cannot test this).

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Doesn't the FreeNAS plugin jail update to the stable version for you? This script is really for PlexPass users which didn't have an easy way to update this when it was created. If you want this to work for non-PlexPass users I would change your PR to add a command line option to change the URL instead of breaking it for it's intended audience.

(The URL worked just fine as is yesterday morning for me, but I have PlexPass)

**Comment by thesymbol** [comment]
Okay might be that, but last time i updated plex on the plugin page i had to recreate the entier database of plex content, and this was working before without plexpass, i dont want to take the risk to update the plugin to have to recreate the entier database again.

Good suggestion to set a parameter option for it tho, will update the pr with that later.

**Comment by thesymbol** [comment]
Updated the code to allow you to specify -n for none plexpass users to download the normal version and if you dont specify -n it will still download the plexpass version.

**Comment by Arcanemagus** [comment]
@mstinaff As this is breaking it for anyone without PlexPass you might want to review this PR :wink:.

**Comment by chipicau** [comment]
hi i tried using the latest script and it tells me update is done but remains with old version

**Comment by Arcanemagus** [comment]
@chipicau are you using the version from this PR?

**Comment by thesymbol** [comment]
It might be related to #6 where it updates but dosent update the version number/says still update available. and the latest version is 0.9.12.18

**Comment by chipicau** [comment]
Yes I'm using that version and the version I have right now is 0.9.12.13

**Comment by chipicau** [comment]
I got it working for some reason it was downloading the update and dumping it on my temp folder but wouldn't update it but I finically got it to update

**Comment by mstinaff** [comment]
@thesymbol Thanks for the fix!  Glad to see people still find this useful.  I should have more time soon to put towards this.

**Comment by mstinaff** [comment]
@chipicau what did you have to change to get it to update?

**Comment by chipicau** [comment]
I used this ./PMS_Updater.sh -n -a -v before I was using just -n but noticed with that it was just downloading it and that I added the -a to install it and used the -v to see everything that was happening to see if any errors came up but went through ok Still kinda new to all this sorry

**Comment by thesymbol** [comment]
@mstinaff Thanks for the initial script and for merging the pull request :+1: still wierd that the plexpass url isnt working for some and for others it is.

@chipicau Ah yes you need to specify -a to get it to install the downloaded update, since it only downloads without it, (its good that it dosent install automatically since if you just want to fetch the update and then run the script again with -a it will not have to download the update).

**Comment by chipicau** [comment]
Yea I realized that after awhile lol. Thanks for all the help

**Comment by wassupdoc** [comment]
I am a plexpass user and was using the script successfully until a few days ago.  Now it gives me the following even after updating to the latest script:
````
Using URL https://plex.tv/downloads?channel=plexpass
Downloading https://plex.tv/downloads?channel=plexpass
--2015-11-03 13:53:02--  https://plex.tv/downloads?channel=plexpass
Resolving plex.tv (plex.tv)... 184.72.61.129, 50.18.56.37, 184.169.183.121, ...
Connecting to plex.tv (plex.tv)|184.72.61.129|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://plex.tv/users/sign_in [following]
--2015-11-03 13:53:03--  https://plex.tv/users/sign_in
Connecting to plex.tv (plex.tv)|184.72.61.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Last-modified header missing -- time-stamps turned off.
--2015-11-03 13:53:03--  https://plex.tv/users/sign_in
Reusing existing connection to plex.tv:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: '/tmp/downloads?channel=plexpass'

    [ <=>                                   ] 15,003      --.-K/s   in 0.07s   

2015-11-03 13:53:04 (225 KB/s) - '/tmp/downloads?channel=plexpass' saved [15003]

Download Complete
Searching https://plex.tv/downloads?channel=plexpass for PlexMediaServer-[0-9]*.[0-9]*.[0-9]*.[0-9]*.[0-9]*-[0-9,a-f]*-freebsd-amd64.tar.bz2 .....Could not find a PlexMediaServer-[0-9]*.[0-9]*.[0-9]*.[0-9]*.[0-9]*-[0-9,a-f]*-freebsd-amd64.tar.bz2 download link on page https://plex.tv/downloads?channel=plexpass
````

**Comment by thesymbol** [comment]
@wassupdoc This PR only solved the non-plexpass download, we have to find the new plexpass url and replace the old plexpass url, if there even is a new url.

**Comment by wassupdoc** [comment]
thanks @thesymbol 
Manually downloading the latest plexpass release from plex site links to this address "https://downloads.plex.tv/plex-media-server/0.9.12.18.1520-6833552/PlexMediaServer-0.9.12.18.1520-6833552-freebsd-amd64.tar.bz2" 
Does that help?

**Comment by thesymbol** [comment]
It is the same as the normal version, its wierd but just use the -n parameter for the script for now and well see if they release anything special for plexpass users down the road.

**Comment by Arcanemagus** [comment]
As of this moment PlexPass and "normal" are both the same version btw, if you were expecting them to be different...

**Comment by thesymbol** [comment]
okay that explains it thanks @Arcanemagus

**Comment by floristenhove** [comment]
Any news on this guys? I see that there's a new plexpass version available now (0.9.14.1).

https://downloads.plex.tv/plex-media-server/0.9.14.1.1544-651f92a/PlexMediaServer-0.9.14.1.1544-651f92a-freebsd-amd64.tar.bz2

**Comment by thesymbol** [comment]
I will take a look when i get home if there is anything changed on the urls.

**Comment by vincegre** [comment]
For me script works still works like a charm without changing anything ! My plex pass server is currently in 0.9.14.1 which is the most recent version automatically !

**Comment by floristenhove** [comment]
I'm getting the same result as @wassupdoc

See http://f.cl.ly/items/0h2W201D1v2y46430Y1G/rootplexmediaserver1varplex%20%20P.txt

**Comment by Arcanemagus** [comment]
The URL hasn't changed for PlexPass...

@floristenhove or @wassupdoc can you see what was actually downloaded to `/tmp/downloads?channel=plexpass` and verify it's actually grabbing the page properly?

**Comment by floristenhove** [comment]
@Arcanemagus here it is: http://f.blck.lv/text/1E1U2L3V1M0x/rootplexmediaserver1tmp%20%20cat%20d.txt

**Comment by Arcanemagus** [comment]
Looks like your credentials didn't work, that looks like a sign in page to me.

**Comment by floristenhove** [comment]
Ok, kill me now. That was it... I changed my password way back but never changed it in my credentials file on the server. Not sure why it worked before. Thank you for your help, I feel really stupid now :flushed:

**Comment by thesymbol** [comment]
Id have to agree with @Arcanemagus it is a sign in page, or looks like it anyway.

**Comment by Arcanemagus** [comment]
It probably "worked" because that URL used to just give you the public downloads if you weren't signed in, now it gives nothing unless you sign in.

**Comment by floristenhove** [comment]
Sounds legit.

**Comment by thesymbol** [comment]
I think i noticed a bit of text saying failed in the document @floristenhove linked to so they might have changed it so that if you fail to login it gives an error. I will try and see what happens if i use a normal account it might just be that normal users need to login on that page too now. But in any case it works now with -n and without :)

**Comment by wassupdoc** [comment]
Yup I noticed my mistake as well was with a password I changed a little while back...now I've updated and everything seems to be working fine.  Sorry about that!

**Pull request merged**
